- args:
    sql: CREATE EXTENSION IF NOT EXISTS pgcrypto;
  type: run_sql
- args:
    sql: CREATE TABLE "public"."users"("id" uuid NOT NULL DEFAULT gen_random_uuid(),
      "email" text NOT NULL, PRIMARY KEY ("id") , UNIQUE ("id"), UNIQUE ("email"));
  type: run_sql
- args:
    name: users
    schema: public
  type: add_existing_table_or_view
