- args:
    cascade: false
    read_only: false
    sql: ALTER TABLE "public"."users" ADD COLUMN "created_at" date;
  type: run_sql
- args:
    cascade: false
    read_only: false
    sql: ALTER TABLE "public"."users" ALTER COLUMN "created_at" DROP NOT NULL;
  type: run_sql
- args:
    cascade: false
    read_only: false
    sql: ALTER TABLE "public"."users" ALTER COLUMN "created_at" SET DEFAULT now();
  type: run_sql
