- args:
    role: user
    table:
      name: users
      schema: public
  type: drop_select_permission
- args:
    permission:
      allow_aggregations: false
      columns:
      - created_at
      - display_name
      - email
      - updated_at
      computed_fields: []
      filter:
        uid:
          _eq: X-Hasura-User-Id
    role: user
    table:
      name: users
      schema: public
  type: create_select_permission
