- args:
    cascade: false
    read_only: false
    sql: |-
      alter table "public"."pushes"
                 add constraint "pushes_user_uid_fkey"
                 foreign key ("user_uid")
                 references "public"."users"
                 ("uid") on update restrict on delete restrict;
  type: run_sql
