- args:
    permission:
      backend_only: false
      check: {}
      columns:
      - email
      filter:
        uid:
          _eq: X-Hasura-User-Id
      set: {}
    role: user
    table:
      name: users
      schema: public
  type: create_update_permission
