- args:
    permission:
      backend_only: false
      filter:
        _exists:
          _table:
            name: users
            schema: public
          _where:
            uid:
              _eq: X-Hasura-User-Id
    role: user
    table:
      name: push_tokens
      schema: public
  type: create_delete_permission
