- args:
    permission:
      allow_aggregations: false
      backend_only: false
      columns:
      - display_name
      - uid
      computed_fields: []
      filter: {}
      limit: null
    role: user
    table:
      name: profiles
      schema: public
  type: create_select_permission
