- args:
    permission:
      allow_aggregations: false
      backend_only: false
      columns:
      - email
      computed_fields: []
      filter:
        uid:
          _eq: X-Hasura-User-Id
      limit: null
    role: user
    table:
      name: users
      schema: public
  type: create_select_permission
