version: 2
tables:
- table:
    schema: public
    name: image_uploads
  object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_uid
  insert_permissions:
  - role: user
    permission:
      check:
        _exists:
          _where:
            uid:
              _eq: X-Hasura-User-Id
          _table:
            schema: public
            name: users
      set:
        user_uid: x-hasura-User-Id
      columns:
      - asset_id
      - image_url
      backend_only: false
  select_permissions:
  - role: user
    permission:
      columns:
      - asset_id
      - id
      - image_url
      filter:
        user_uid:
          _eq: X-Hasura-User-Id
- table:
    schema: public
    name: users
  insert_permissions:
  - role: user
    permission:
      check: {}
      set:
        uid: x-hasura-User-Id
      columns:
      - email
      backend_only: false
  select_permissions:
  - role: user
    permission:
      columns:
      - email
      filter:
        uid:
          _eq: X-Hasura-User-Id
  update_permissions:
  - role: user
    permission:
      columns:
      - email
      filter:
        uid:
          _eq: X-Hasura-User-Id
      check: {}
  delete_permissions:
  - role: user
    permission:
      filter:
        uid:
          _eq: X-Hasura-User-Id
