version: 2
tables:
- table:
    schema: public
    name: image_uploads
  object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_uid
  insert_permissions:
  - role: user
    permission:
      check:
        _exists:
          _where:
            uid:
              _eq: X-Hasura-User-Id
          _table:
            schema: public
            name: users
      set:
        user_uid: x-hasura-User-Id
      columns:
      - asset_id
      - image_url
      backend_only: false
  select_permissions:
  - role: user
    permission:
      columns:
      - asset_id
      - created_at
      - id
      - image_url
      filter:
        user_uid:
          _eq: X-Hasura-User-Id
- table:
    schema: public
    name: push_tokens
  object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_uid
  insert_permissions:
  - role: user
    permission:
      check:
        _exists:
          _where:
            uid:
              _eq: X-Hasura-User-Id
          _table:
            schema: public
            name: users
      set:
        user_uid: x-hasura-User-Id
      columns:
      - token
      backend_only: false
  select_permissions:
  - role: user
    permission:
      columns:
      - created_at
      - token
      filter:
        _exists:
          _where:
            uid:
              _eq: X-Hasura-User-Id
          _table:
            schema: public
            name: users
  delete_permissions:
  - role: user
    permission:
      filter:
        _exists:
          _where:
            uid:
              _eq: X-Hasura-User-Id
          _table:
            schema: public
            name: users
- table:
    schema: public
    name: pushes
  object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_uid
  event_triggers:
  - name: invoke_push
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      num_retries: 0
      interval_sec: 10
      timeout_sec: 60
    webhook: https://marie.anais.dev/invoke-push
- table:
    schema: public
    name: users
  array_relationships:
  - name: image_uploads
    using:
      foreign_key_constraint_on:
        column: user_uid
        table:
          schema: public
          name: image_uploads
  - name: push_tokens
    using:
      foreign_key_constraint_on:
        column: user_uid
        table:
          schema: public
          name: push_tokens
  - name: pushes
    using:
      foreign_key_constraint_on:
        column: user_uid
        table:
          schema: public
          name: pushes
  insert_permissions:
  - role: user
    permission:
      check: {}
      set:
        uid: x-hasura-User-Id
      columns:
      - email
      backend_only: false
  select_permissions:
  - role: user
    permission:
      columns:
      - created_at
      - email
      - updated_at
      filter:
        uid:
          _eq: X-Hasura-User-Id
  update_permissions:
  - role: user
    permission:
      columns:
      - email
      filter:
        uid:
          _eq: X-Hasura-User-Id
      check: {}
  delete_permissions:
  - role: user
    permission:
      filter:
        uid:
          _eq: X-Hasura-User-Id
