- args:
    permission:
      allow_upsert: true
      backend_only: false
      check: {}
      columns:
      - token
      set:
        user_uid: x-hasura-User-Id
    role: user
    table:
      name: push_tokens
      schema: public
  type: create_insert_permission
