- args:
    permission:
      backend_only: false
      filter:
        uid:
          _eq: X-Hasura-User-Id
    role: user
    table:
      name: users
      schema: public
  type: create_delete_permission
