- args:
    cascade: false
    read_only: false
    sql: ALTER TABLE "public"."users" ADD COLUMN "id" uuid;
  type: run_sql
- args:
    cascade: false
    read_only: false
    sql: ALTER TABLE "public"."users" ALTER COLUMN "id" DROP NOT NULL;
  type: run_sql
- args:
    cascade: false
    read_only: false
    sql: ALTER TABLE "public"."users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  type: run_sql
